### ISSUE TITLE
No me funciona con VPN

### ISSUE THREAD

**Issue by lesclaz** [qvapay/qp#14]
Cuando tengo el VPN activo la app no me funciona, supongo que puede ser por la protección de CloudFlare, me suele salir un captcha de CloudFlare en varios sitios cuando uso vpn.

https://github.com/qvapay/qp/assets/22064368/38df6b3d-5906-44a7-ba43-3d6c04b40239

**Comment by n3omaster** [comment]
Country?

**Comment by lesclaz** [comment]
> Country?

Me conecto desde Cuba, y el VPN sale por EE.UU. 🇺🇸 y en ocasiones por Países Bajos 🇳🇱 (ProtonVPN versión gratuita)
