### ISSUE TITLE
Feedback 

### ISSUE THREAD

**Issue by esalessandrxx** [qvapay/qp#18]
Aquí dos recomendaciones de cosas que creo se podrían mejorar.

1- Mis Compras: en este apartado se podría mejorar que cuando expire la tarjeta adquirida ya no se muestre más.

2- Tarjeta: aquí se podría mejorar como se visualiza los datos de la tarjeta, actualmente se muestra el código Json y ya, se podría mejorar visualmente para que salga:

Nombre: Alessandro
Tarjeta: `40738 4993 0000 0000`
Expira: 11/23
CVV: `000`

Al lado del CVV y número de tarjeta se podría agregar un icono de copiar, asi el usuario solo tendría que presionarlo y se le copian esos dos datos al portapapeles.

Saludos.

**Comment by n3omaster** [comment]
Fixed en la v2.1
