### ISSUE TITLE
GOLD CHECK

### ISSUE THREAD

**Issue by esalessandrxx** [qvapay/qp#7]
Al querer adquirir el Gold Check la aplicación sufre un cierre inesperado. 

Android: 13
Samsung S20 Fe

**Comment by n3omaster** [comment]
Hola, puede por favor explicar detalladamente los que le sucede?

**Comment by esalessandrxx** [comment]
Cuándo entro a la aplicación y abro mi perfil sale `Comprar GOLD Check` al presionar encima para comprarlo, la aplicación se cierra.

No se si pueda influir, pero no tengo balance en mi cuenta, quizás sea eso lo que lo provoca.

**Comment by n3omaster** [comment]
Fixed with balance validation and error handle if status 422
